// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReGranBill.Server.Data;

#nullable disable

namespace ReGranBill.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReGranBill.Server.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.BankDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("bank_details", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("LogoBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("company_settings", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Formulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseInputKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(100m);

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("formulations", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.FormulationLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AmountPerBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("BagsPerBase")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("FormulationId")
                        .HasColumnType("integer");

                    b.Property<string>("LineKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FormulationId");

                    b.ToTable("formulation_lines", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.InventoryLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("OriginalQty")
                        .HasColumnType("integer");

                    b.Property<decimal>("OriginalWeightKg")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int?>("ParentLotId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceVoucherId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceVoucherType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("VendorAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LotNumber");

                    b.HasIndex("ParentLotId");

                    b.HasIndex("ProductAccountId");

                    b.HasIndex("SourceEntryId");

                    b.HasIndex("SourceVoucherId");

                    b.HasIndex("VendorAccountId");

                    b.ToTable("inventory_lots", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("LotId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("QtyDelta")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("ValueDelta")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("VoucherId")
                        .HasColumnType("integer");

                    b.Property<string>("VoucherLineKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("WeightKgDelta")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductAccountId");

                    b.HasIndex("VoucherId");

                    b.HasIndex("LotId", "TransactionDate", "Id");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.InventoryVoucherLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("LotId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("VoucherId")
                        .HasColumnType("integer");

                    b.Property<string>("VoucherLineKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("VoucherId", "VoucherType", "VoucherLineKey");

                    b.ToTable("inventory_voucher_links", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ActualWeightKg")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LineKind")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Qty")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Rbp")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("VoucherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("VoucherId");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.JournalVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RatesAdded")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("VoucherNumber")
                        .IsUnique();

                    b.ToTable("journal_vouchers", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.JournalVoucherReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MainVoucherId")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceVoucherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MainVoucherId")
                        .IsUnique();

                    b.HasIndex("ReferenceVoucherId")
                        .IsUnique();

                    b.HasIndex("MainVoucherId", "ReferenceVoucherId")
                        .IsUnique();

                    b.ToTable("journal_voucher_references", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.PartyDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PartyRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("party_details", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Packing")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PackingWeightKg")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("product_details", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.RolePage", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("PageKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RoleId", "PageKey");

                    b.ToTable("role_pages", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.VehicleOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedVehicleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedVehicleNumber")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("vehicle_options", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.VoucherCounter", b =>
                {
                    b.Property<string>("SequenceKey")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sequence_key");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.HasKey("SequenceKey");

                    b.ToTable("voucher_counters", (string)null);
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Account", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.Category", "Category")
                        .WithMany("Accounts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.BankDetail", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.Account", "Account")
                        .WithOne("BankDetail")
                        .HasForeignKey("ReGranBill.Server.Entities.BankDetail", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Formulation", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.FormulationLine", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.Formulation", "Formulation")
                        .WithMany("Lines")
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Formulation");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.InventoryLot", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.InventoryLot", "ParentLot")
                        .WithMany("ChildLots")
                        .HasForeignKey("ParentLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReGranBill.Server.Entities.Account", "ProductAccount")
                        .WithMany()
                        .HasForeignKey("ProductAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.JournalEntry", "SourceEntry")
                        .WithMany()
                        .HasForeignKey("SourceEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReGranBill.Server.Entities.JournalVoucher", "SourceVoucher")
                        .WithMany()
                        .HasForeignKey("SourceVoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.Account", "VendorAccount")
                        .WithMany()
                        .HasForeignKey("VendorAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLot");

                    b.Navigation("ProductAccount");

                    b.Navigation("SourceEntry");

                    b.Navigation("SourceVoucher");

                    b.Navigation("VendorAccount");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.InventoryLot", "Lot")
                        .WithMany("Transactions")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.Account", "ProductAccount")
                        .WithMany()
                        .HasForeignKey("ProductAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.JournalVoucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("ProductAccount");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.InventoryVoucherLink", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.InventoryLot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.InventoryTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.JournalVoucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("Transaction");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.JournalEntry", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.JournalVoucher", "JournalVoucher")
                        .WithMany("Entries")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalVoucher");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.JournalVoucher", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.JournalVoucherReference", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.JournalVoucher", "MainVoucher")
                        .WithMany()
                        .HasForeignKey("MainVoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReGranBill.Server.Entities.JournalVoucher", "ReferenceVoucher")
                        .WithMany()
                        .HasForeignKey("ReferenceVoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainVoucher");

                    b.Navigation("ReferenceVoucher");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.PartyDetail", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.Account", "Account")
                        .WithOne("PartyDetail")
                        .HasForeignKey("ReGranBill.Server.Entities.PartyDetail", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.ProductDetail", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.Account", "Account")
                        .WithOne("ProductDetail")
                        .HasForeignKey("ReGranBill.Server.Entities.ProductDetail", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.RolePage", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.Role", "Role")
                        .WithMany("Pages")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.User", b =>
                {
                    b.HasOne("ReGranBill.Server.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Account", b =>
                {
                    b.Navigation("BankDetail");

                    b.Navigation("PartyDetail");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Category", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Formulation", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.InventoryLot", b =>
                {
                    b.Navigation("ChildLots");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.JournalVoucher", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("ReGranBill.Server.Entities.Role", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
